services:
  productstore-db:
    image: postgres:17.1-alpine3.20
    container_name: productstore-db
    environment:
      - POSTGRES_DB=productstore-db
      - POSTGRES_USER=productstore-user
      - POSTGRES_PASSWORD=productstore-password
    ports:
      - "5432:5432"
    volumes:
      - productstore-db:/var/lib/postgresql/data

volumes:
  productstore-db:
